# Exemplo de configuração de secrets para o Streamlit
# Este arquivo deve ser colocado em .streamlit/secrets.toml
# NUNCA commite este arquivo no repositório!

# Configurações do Google Sheets
[google_sheets]
# Configurações da planilha
spreadsheet_url = "https://docs.google.com/spreadsheets/d/SEU_ID_DA_PLANILHA/edit"
worksheet_name = "NOME_DA_ABA"

# Credenciais da conta de serviço do Google
project_id = "seu-projeto-id"
private_key_id = "sua-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nSUA_CHAVE_PRIVADA_AQUI\n-----END PRIVATE KEY-----\n"
client_email = "seu-service-account@seu-projeto.iam.gserviceaccount.com"
client_id = "seu-client-id"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/seu-service-account%40seu-projeto.iam.gserviceaccount.com"

# Instruções:
# 1. Copie este arquivo para .streamlit/secrets.toml na raiz do seu projeto
# 2. Substitua os valores de exemplo pelos seus dados reais
# 3. Adicione .streamlit/secrets.toml ao seu .gitignore
# 4. Para deploy no Streamlit Cloud, configure os secrets na interface web